### ISSUE TITLE
If the transform function is called with a value larger than max, we get a crash

### ISSUE THREAD

**Issue by sudhanshuraheja** [aldente0630/gauss_rank_scaler#1]
For example, if we try this

a1 = np.array([0, 1, 2, 3, 57]).reshape(-1, 1)
sc = GaussRankScaler()
print(sc.fit_transform(a1))

a2 = np.array([0, 1, 2, 3, 84]).reshape(-1, 1)
print(sc.transform(a2))

The script crashed on check_array.

Would you have any suggestions on fixing this?

**Comment by jkmackie** [comment]
@sudhanshuraheja 
The "out-of-bounds" issue is in this code block:
```
def _transform(self, i, x):
        return erfinv(self.interp_func_[i](x))
```
The domain of erfinv is restricted to -1<x<1.  So x outside this domain must be clipped.  Otherwise, erfinv will return -inf or inf.

Here is the quick fix:

```
    def _transform(self, i, x):        
        bound = 1.0 - self.epsilon
        clipped = np.clip(self.interp_func_[i](x), -bound, bound)
        return erfinv(clipped)
```

Note the ```bound``` variable here is _redundant_ with the bound in ```_fit()```.  So ```bound``` should be added as ```self.bound  = 1 - epsilon``` under ```def __init__()```.  Then rewrite my quick fix with self.bound.

My solution works on the Boston dataset.  It prevents NaN insertion by erfinv for x values (in test) outside the erfinv domain.

**Comment by bits-bytes-nn** [comment]
Cool! It's been a long time, but I applied the solution mentioned by @jkmackie . Thank you!
